name: Build & Deploy Jekyll site to GitHub Pages
on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # 0) system deps — add ImageMagick
      - run: sudo apt-get update && sudo apt-get install -y imagemagick

      # 1) Ruby + gems (now pulls jekyll‑scholar 7.x)
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      # 2) Build
      - run: bundle exec jekyll build -d _site

      # 3) Upload & deploy
      - uses: actions/upload-pages-artifact@v3
        with: {path: ./_site}
      - uses: actions/deploy-pages@v4
